### ISSUE TITLE
PayUSDK is not API level 26

### ISSUE THREAD

**Issue by shivenkumar79** [payu-intrepos/PayUMoney-Android-SDK#6]
Having now Android mandate API level 26 for Apps, current version of SDK seems to be written in 23.5. Could you please have the SDK in 26.x or above? When trying to integrate the current version, it results in Dex/manifest merge errors

**Comment by hargoyal** [comment]
Same here getting ERR_CLEARTEXT_NOT_PERMIT on Android Pie (API 26).
If I try to add android:usesCleartextTraffic="true" in my manifest, getting manifest merging error.

![screenshot_1551261092](https://user-images.githubusercontent.com/16696932/53620884-8f269f00-3c1a-11e9-8cca-f4e6182f1324.png)

How can i handle this issue?

**Comment by JagadishaIncture** [comment]
> Same here getting ERR_CLEARTEXT_NOT_PERMIT on Android Pie (API 26).
> If I try to add android:usesCleartextTraffic="true" in my manifest, getting manifest merging error.
> 
> ![screenshot_1551261092](https://user-images.githubusercontent.com/16696932/53620884-8f269f00-3c1a-11e9-8cca-f4e6182f1324.png)
> 
> How can i handle this issue?

Any solution?

**Comment by JagadishaIncture** [comment]
Use the latest dependency

compile 'com.payumoney.sdkui:plug-n-play:1.6.0'

and change minSdkversion

minSdkVersion 20

and in Manifest add this

tools:replace="android:allowBackup,android:usesCleartextTraffic"

**Comment by Rahul-Hooda** [comment]
PayU SDKs are using compile version 26. Please use the latest PnP SDK -
implementation 'com.payumoney.sdkui:plug-n-play:1.6.0'

@JagadishaIncture - The issue of cleartext not permitted is because only https url are supported inside the Custom Browser's webview for transaction. However, in Test environment, axis emulator is loaded which is http url. So, as you mentioned, you can fix it for testing purpose with tools:replace="android:allowBackup,android:usesCleartextTraffic"

P.S : This error will not occur on Prod environment, because actual bank pages are loaded on prod that are https.
